language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t danny/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danny/docker-react npm run test

  